show databases;
create database college; 
use college;
create table students(id int not null,name varchar(25) not null,father_name varchar(25) not null,cid int not null,rollno bigint not null,primary key(id));
show tables;
describe students;
insert into students(id,name,father_name,gender,cid,rollno)values(null,'gopi','koteswrarao','male','2','43'),(null,'ramesh','narayana','male','3','30');
alter table students add gender varchar(25) not null after father_name;
alter table students modify id int not null auto_increment;
select * from students;
select id,name,father_name from students;
update students set name ='rameshgopi' where id=2;
delete from students where id=1;
